### ISSUE TITLE
Спасибо

### ISSUE THREAD

**Issue by Dmitry-cybe** [DRMPN/ATP-and-IP#1]

**Comment by Dmitry-cybe** [comment]
Есть ли решение 8ого задания?

**Comment by DRMPN** [comment]
Да - https://github.com/DRMPN/ATP-and-IP/blob/master/Task_ImageAI_2023_YOLO_TF_2.ipynb

Я по 1 файлу прогонял и результаты заносил количество в таблицу:

![image](https://github.com/DRMPN/ATP-and-IP/assets/61294398/613d8fb0-2b49-4ab1-be2c-f9373f0a46cc)

**Comment by Dmitry-cybe** [comment]
Спасибо огромное, очень выручил!
